FROM rust:1-bookworm as build

ARG CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++ 

ARG PKG_CONFIG_ALLOW_CROSS=1
ARG PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}"

RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /bin

WORKDIR /app

COPY justfile justfile

# Unwrap build-player target to take advantage of caching
RUN just install-deps aarch64-unknown-linux-gnu
RUN just add-target aarch64-unknown-linux-gnu
RUN just install-toolchain "stable" aarch64-unknown-linux-gnu
RUN just install-sqlx

COPY . .

ARG DATABASE_URL="sqlite:///tmp/data.db"
RUN just reset-database
RUN just build-www
RUN just build-bin hifi-rs aarch64-unknown-linux-gnu

RUN mv target/aarch64-unknown-linux-gnu/release/hifi-rs /usr/local/bin

FROM scratch

COPY --from=build /usr/local/bin/hifi-rs .

ENTRYPOINT ["./hifi-rs"]
